### ISSUE TITLE
The create-wave-app command should allow the user to pass in the app name as an argument

### ISSUE THREAD

**Issue by jacobgranberry** [companydotcom/vastly#163]
Running `create-wave-app` starts a prompt that asks what you want to name the app.  It would be a nice QOL feature to be able to pass in a name as an argument to the command, and have it auto populate that prompt field

`create-wave-app appName` for example

**Comment by ctbwx** [comment]
Tracking in Jira--closing issue: https://companydotcom.atlassian.net/browse/ATX-2805
