### ISSUE TITLE
Vastly CLI - Documentation Issues

### ISSUE THREAD

**Issue by eratik** [companydotcom/vastly#212]
There are a couple of issues on the Vastly CLI:

1. npx i -g @vastly/cli - Doesn't work... Should be npm i -g @vastly/cli (npx doesn't install globally by design)
2. Available command links (login, env, etc) are all 404.  Just needs to be wired up to the appropriate pages

**Comment by ctbwx** [comment]
Closing issue--separate doc for Documentation tracking: https://www.notion.so/govastly/docs-vastly-is-Living-Backlog-0776e11a2e0c430fa42b3968761571e5?pvs=4
